variable "prefix" {}
variable "env" {}
variable "gcp_project_id" {}
variable "primary_region" {}
variable "min_gke_master_version" {}
variable "gke_machine_type" {}
variable "gke_type" {}
variable "postgres_instance_name" {}
variable "psql_db" {}
variable "psql_user" {}
